<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE_ABSTRACT."APIKey.php";
/**
 * Class APIKeyTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/APIKeyTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 22:36:00.
 *
 */
class APIKeyTest 
    extends PHPUnit_Framework_TestCase
{
    /**
     * @var object APIKey an instance of APIKey
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new APIKey();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSetApplication
     *
     * @covers APIKey::setApplication
     *
     * @todo   Implement testSetApplication().
     *
     * @return void
     */
    public function testSetApplication()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetApplication
     *
     * @covers APIKey::getApplication
     *
     * @todo   Implement testGetApplication().
     *
     * @return void
     */
    public function testGetApplication()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetExpiration
     *
     * @covers APIKey::setExpiration
     *
     * @todo   Implement testSetExpiration().
     *
     * @return void
     */
    public function testSetExpiration()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetExpiration
     *
     * @covers APIKey::getExpiration
     *
     * @todo   Implement testGetExpiration().
     *
     * @return void
     */
    public function testGetExpiration()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetKey
     *
     * @covers APIKey::setKey
     *
     * @todo   Implement testSetKey().
     *
     * @return void
     */
    public function testSetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetKey
     *
     * @covers APIKey::getKey
     *
     * @todo   Implement testGetKey().
     *
     * @return void
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetLimit
     *
     * @covers APIKey::setLimit
     *
     * @todo   Implement testSetLimit().
     *
     * @return void
     */
    public function testSetLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetLimit
     *
     * @covers APIKey::getLimit
     *
     * @todo   Implement testGetLimit().
     *
     * @return void
     */
    public function testGetLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetRequests
     *
     * @covers APIKey::setRequests
     *
     * @todo   Implement testSetRequests().
     *
     * @return void
     */
    public function testSetRequests()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetRequests
     *
     * @covers APIKey::getRequests
     *
     * @todo   Implement testGetRequests().
     *
     * @return void
     */
    public function testGetRequests()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetResponses
     *
     * @covers APIKey::setResponses
     *
     * @todo   Implement testSetResponses().
     *
     * @return void
     */
    public function testSetResponses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetResponses
     *
     * @covers APIKey::getResponses
     *
     * @todo   Implement testGetResponses().
     *
     * @return void
     */
    public function testGetResponses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGenerate
     *
     * @covers APIKey::generate
     *
     * @todo   Implement testGenerate().
     *
     * @return void
     */
    public function testGenerate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testRenew
     *
     * @covers APIKey::renew
     *
     * @todo   Implement testRenew().
     *
     * @return void
     */
    public function testRenew()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testResetCounters
     *
     * @covers APIKey::resetCounters
     *
     * @todo   Implement testResetCounters().
     *
     * @return void
     */
    public function testResetCounters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
