<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE . "databaseQueryPrepared.php";
/**
 * Class databaseQueryPreparedTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/databaseQueryPreparedTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-09 at 23:35:57.
 *
 */
class databaseQueryPreparedTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object databaseQueryPrepared an instance of databaseQueryPrepared
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new databaseQueryPrepared();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }
}
