<?php
require_once __DIR__ . DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."config".DIRECTORY_SEPARATOR."config.inc.php";
require_once AMPHIBIAN_CORE_ABSTRACT . "DataList.php";
require_once AMPHIBIAN_TESTS."baseTest.php";
/**
 * Class datalistTest
 *
 * @category Test
 * @package  Core
 * @author   Carl "Tex" Morgan <texmorgan@amphibian.co>
 * @license  
 * @link     documentation/datalistTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 17:05:31.
 *
 */
class datalistTest 
	extends BaseTest
{
    /**
     * @var object datalist an instance of datalist
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new datalist();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers datalist::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetClass
     *
     * @covers datalist::setClass
     *
     * @todo   Implement testSetClass().
     *
     * @return void
     */
    public function testSetClass()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetHtml
     *
     * @covers datalist::getHtml
     *
     * @todo   Implement testGetHtml().
     *
     * @return void
     */
    public function testGetHtml()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetId
     *
     * @covers datalist::setId
     *
     * @todo   Implement testSetId().
     *
     * @return void
     */
    public function testSetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetTitle
     *
     * @covers datalist::setTitle
     *
     * @todo   Implement testSetTitle().
     *
     * @return void
     */
    public function testSetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetPlaceholder
     *
     * @covers datalist::setPlaceholder
     *
     * @todo   Implement testSetPlaceholder().
     *
     * @return void
     */
    public function testSetPlaceholder()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetLabelFields
     *
     * @covers datalist::setLabelFields
     *
     * @todo   Implement testSetLabelFields().
     *
     * @return void
     */
    public function testSetLabelFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetName
     *
     * @covers datalist::setName
     *
     * @todo   Implement testSetName().
     *
     * @return void
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetLabel
     *
     * @covers datalist::setLabel
     *
     * @todo   Implement testSetLabel().
     *
     * @return void
     */
    public function testSetLabel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetQuery
     *
     * @covers datalist::setQuery
     *
     * @todo   Implement testSetQuery().
     *
     * @return void
     */
    public function testSetQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetQuery
     *
     * @covers datalist::getQuery
     *
     * @todo   Implement testGetQuery().
     *
     * @return void
     */
    public function testGetQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetValueField
     *
     * @covers datalist::setValueField
     *
     * @todo   Implement testSetValueField().
     *
     * @return void
     */
    public function testSetValueField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetValueField
     *
     * @covers datalist::getValueField
     *
     * @todo   Implement testGetValueField().
     *
     * @return void
     */
    public function testGetValueField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetSeparatorFields
     *
     * @covers datalist::setSeparatorFields
     *
     * @todo   Implement testSetSeparatorFields().
     *
     * @return void
     */
    public function testSetSeparatorFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers datalist::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testShowHTML
     *
     * @covers datalist::showHTML
     *
     * @todo   Implement testShowHTML().
     *
     * @return void
     */
    public function testShowHTML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testWrite
     *
     * @covers datalist::write
     *
     * @todo   Implement testWrite().
     *
     * @return void
     */
    public function testWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
