<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE . "Loader.php";
/**
 * Class LoaderTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/LoaderTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-09 at 23:35:33.
 *
 */
class LoaderTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object Loader an instance of Loader
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new Loader();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSet
     *
     * @covers Loader::set
     *
     * @todo   Implement testSet().
     *
     * @return void
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGet
     *
     * @covers Loader::get
     *
     * @todo   Implement testGet().
     *
     * @return void
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers Loader::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
