<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_GENERATORS_MYSQLI . "classGeneratorMySQLi.php";
/**
 * Class classGeneratorMySQLiTest
 *
 * @category UnitTests
 * @package  ClassGeneratorMySQLi
 * @author   Carl "Tex" Morgan <texmorgan@amphibian.co>
 * @license  GPL v3
 * @link     documentation/classGeneratorMySQLiTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-13 at 20:00:32.
 *
 */
class classGeneratorMySQLiTest 
    extends BaseTest
{
    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->connection = DatabaseConnectionMySQLi::factory();
        $this->connection->setServerName("localhost");
        $this->connection->setDatabaseName("InnerAlly");
        $this->connection->setUserName("root");
        $this->connection->setUserPassword('4u$t1nTX');
        $this->connection->openConnection();
        $this->object = ClassGeneratorMySQLi::factory($this->connection);
    }

    /** testInstance
     *
     * @covers ClassGeneratorMySQLi::instance
     *
     * @return void
     */
    public function testInstance()
    {
        $this->expected = $this->object;
        $this->actual = ClassGeneratorMySQLi::instance($this->connection);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testFactory
     *
     * @covers ClassGeneratorMySQLi::factory
     *
     * @return void
     */
    public function testFactory()
    {
        $this->expected = $this->object;
        $this->actual = ClassGeneratorMySQLi::factory($this->connection);
        $this->assertEquals($this->expected, $this->actual);
    }
}
