<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";

require_once AMPHIBIAN_GENERATORS_MYSQLI."DatabaseBackupMySQLi.php";
/**
 * Class DatabaseBackupMySQLiTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/DatabaseBackupMySQLiTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:29:21.
 *
 */
class DatabaseBackupMySQLiTest 
    extends PHPUnit_Framework_TestCase
{
    /**
     * @var object DatabaseBackupMySQLi an instance of DatabaseBackupMySQLi
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new DatabaseBackupMySQLi();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers DatabaseBackupMySQLi::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testFactory
     *
     * @covers DatabaseBackupMySQLi::factory
     *
     * @todo   Implement testFactory().
     *
     * @return void
     */
    public function testFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetNoData
     *
     * @covers DatabaseBackupMySQLi::setNoData
     *
     * @todo   Implement testSetNoData().
     *
     * @return void
     */
    public function testSetNoData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
