<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_GENERATORS_MYSQLI."DecoratorGeneratorMySQLi.php";
/**
 * Class DecoratorGeneratorMySQLiTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/DecoratorGeneratorMySQLiTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:31:43.
 *
 */
class DecoratorGeneratorMySQLiTest 
    extends BaseTest
{
    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = DecoratorGeneratorMySQLi::factory($this->connection);
    }

    /** testInstance
     *
     * @covers DecoratorGeneratorMySQLi::instance
     *
     * @return void
     */
    public function testInstance()
    {
        $this->expected = $this->object;
        $this->actual = DecoratorGeneratorMySQLi::instance($this->connection);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testFactory
     *
     * @covers DecoratorGeneratorMySQLi::factory
     *
     * @return void
     */
    public function testFactory()
    {
        $this->expected = $this->object;
        $this->actual = DecoratorGeneratorMySQLi::factory($this->connection);
        $this->assertEquals($this->expected, $this->actual);
    }
}