<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_GENERATORS_MYSQLI."PreloaderGeneratorMySQLi.php";
/**
 * Class PreloaderGeneratorMySQLiTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/PreloaderGeneratorMySQLiTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:43:50.
 *
 */
class PreloaderGeneratorMySQLiTest 
    extends BaseTest
{
    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = PreloaderGeneratorMySQLi::factory($this->connection);
    }

    /** testInstance
     *
     * @covers PreloaderGeneratorMySQLi::instance
     *
     * @return void
     */
    public function testInstance()
    {
        $this->expected = $this->object;
        $this->actual = PreloaderGeneratorMySQLi::instance($this->connection);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testFactory
     *
     * @covers PreloaderGeneratorMySQLi::factory
     *
     * @return void
     */
    public function testFactory()
    {
        $this->expected = $this->object;
        $this->actual = PreloaderGeneratorMySQLi::factory($this->connection);
        $this->assertEquals($this->expected, $this->actual);
    }
}
