<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_GENERATORS_MYSQLI."StandardViewBuilderMySQLi.php";
/**
 * Class StandardViewBuilderMySQLiTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/StandardViewBuilderMySQLiTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:45:53.
 *
 */
class StandardViewBuilderMySQLiTest 
    extends BaseTest
{

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = StandardViewBuilderMySQLi::factory($this->connection);
    }

    /** testInstance
     *
     * @covers StandardViewBuilderMySQLi::instance
     *
     * @return void
     */
    public function testInstance()
    {
        $this->expected = $this->object;
        $this->actual = StandardViewBuilderMySQLi::instance($this->connection);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testFactory
     *
     * @covers StandardViewBuilderMySQLi::factory
     *
     * @return void
     */
    public function testFactory()
    {
        $this->expected = $this->object;
        $this->actual = StandardViewBuilderMySQLi::factory($this->connection);
        $this->assertEquals($this->expected, $this->actual);
    }
}
