<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "config" . DIRECTORY_SEPARATOR . "config.inc.php";
require_once AMPHIBIAN_GENERATORS_ABSTRACT . "BrowseGenerator.php";
require_once MYSQL;
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 13:40:39.
 */
class browseGeneratorTest extends BaseTest
{
    /**
     * @var browseGenerator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $databaseConnection = databaseConnectionMySQLi::instance();
        $this->object = browseGenerator::instance($databaseConnection);
        $this->assertInstanceOf('browseGenerator', $this->object);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers browseGenerator::setTableName
     * @todo   Implement testSetTableName().
     */
    public function testSetTableName( $tableName )
    {
        $this->object->setTableName($tableName);
        $this->assertEquals($tableName, $this->object->currentTableName);
        $this->object->setTableName("");
        $this->assertFalse($tableName, $this->object->currentTableName);
    }

    /**
     * @covers browseGenerator::setTableArray
     * @todo   Implement testSetTableArray().
     */
    public function testSetTableArray( $array )
    {
        $this->object->setTableArray($array);
        $this->object->assertEquals($array, $this->object->tableArray);
    }

    /**
     * @covers browseGenerator::execute
     * @todo   Implement testExecute().
     */
    public function testExecute()
    {
        $this->object->assertEquals(true, $this->object->execute());
    }
}
