<?php
$currentProject="";
/*
 * Local installation variables 
 */
DEFINE('AMPHIBIAN', __DIR__ . DIRECTORY_SEPARATOR . '..'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CONFIG', AMPHIBIAN . 'config'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_CORE', AMPHIBIAN . 'core'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_INTERFACES', AMPHIBIAN_CORE . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_CORE_ABSTRACT', AMPHIBIAN_CORE . 'abstract'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_ABSTRACT_INTERFACES', AMPHIBIAN_CORE_ABSTRACT . 'interfaces'.DIRECTORY_SEPARATOR);
//MariaDB
DEFINE('AMPHIBIAN_CORE_MARIA', AMPHIBIAN_CORE . 'MariaDB'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_MARIA_INTERFACES', AMPHIBIAN_CORE_MARIA . 'interfaces'.DIRECTORY_SEPARATOR);
//MongoDB
DEFINE('AMPHIBIAN_CORE_MONGO', AMPHIBIAN_CORE . 'MongoDB'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_MONGO_INTERFACES', AMPHIBIAN_CORE_MONGO . 'interfaces'.DIRECTORY_SEPARATOR);
//Microsoft SQL
DEFINE('AMPHIBIAN_CORE_MSSQL', AMPHIBIAN_CORE . 'MSSQL'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_MSSQL_INTERFACES', AMPHIBIAN_CORE_MSSQL . 'interfaces'.DIRECTORY_SEPARATOR);
//MySQLi
DEFINE('AMPHIBIAN_CORE_MYSQLI', AMPHIBIAN_CORE . 'MySQLi'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_MYSQLI_INTERFACES', AMPHIBIAN_CORE_MYSQLI . 'interfaces'.DIRECTORY_SEPARATOR);
//Postgre
DEFINE('AMPHIBIAN_CORE_POSTGRE', AMPHIBIAN_CORE . 'Postgre'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_POSTGRE_INTERFACES', AMPHIBIAN_CORE_POSTGRE . 'interfaces'.DIRECTORY_SEPARATOR);
//SQLite
DEFINE('AMPHIBIAN_CORE_SQLITE', AMPHIBIAN_CORE . 'SQLite'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_SQLITE_INTERFACES', AMPHIBIAN_CORE_SQLITE . 'interfaces'.DIRECTORY_SEPARATOR);
//SQLite v3
DEFINE('AMPHIBIAN_CORE_SQLITE3', AMPHIBIAN_CORE . 'SQLite3'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_SQLITE3_INTERFACES', AMPHIBIAN_CORE_SQLITE3 . 'interfaces'.DIRECTORY_SEPARATOR);
//Microsoft SQL Server
DEFINE('AMPHIBIAN_CORE_SQLSVR', AMPHIBIAN_CORE . 'SQLSVR'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_SQLSVR_INTERFACES', AMPHIBIAN_CORE_SQLSVR . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_CORE_HELPERS', AMPHIBIAN_CORE . 'helpers'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_NAMESPACES', AMPHIBIAN_CORE . 'namespaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_CORE_NEUTRAL', AMPHIBIAN_CORE . 'neutral'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_CORE_NEUTRAL_INTERFACES', AMPHIBIAN_CORE_NEUTRAL . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS', AMPHIBIAN . 'generators'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_ABSTRACT', AMPHIBIAN_GENERATORS . 'abstract'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_ABSTRACT_INTERFACES', AMPHIBIAN_GENERATORS_ABSTRACT . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_MARIADB', AMPHIBIAN_GENERATORS . 'MariaDB'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_MARIADB_INTERFACES', AMPHIBIAN_GENERATORS_MARIADB . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_MONGODB', AMPHIBIAN_GENERATORS . 'MongoDB'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_MONGODB_INTERFACES', AMPHIBIAN_GENERATORS_MONGODB . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_MSSQL', AMPHIBIAN_GENERATORS . 'MSSQL'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_MSSQL_INTERFACES', AMPHIBIAN_GENERATORS_MSSQL . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_MYSQLI', AMPHIBIAN_GENERATORS . 'MySQLi'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_MYSQLI_INTERFACES', AMPHIBIAN_GENERATORS_MYSQLI . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_NEUTRAL', AMPHIBIAN_GENERATORS . 'neutral' . DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_NEUTRAL_INTERFACES', AMPHIBIAN_GENERATORS_MYSQLI . 'interfaces' . DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_POSTGRE', AMPHIBIAN_GENERATORS . 'Postgre'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_POSTGRE_INTERFACES', AMPHIBIAN_GENERATORS_POSTGRE . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_SQLITE', AMPHIBIAN_GENERATORS . 'SQLite'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_SQLITE_INTERFACES', AMPHIBIAN_GENERATORS_SQLITE . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_SQLITE3', AMPHIBIAN_GENERATORS . 'SQLite3'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_SQLITE3_INTERFACES', AMPHIBIAN_GENERATORS_SQLITE3 . 'interfaces'.DIRECTORY_SEPARATOR);

DEFINE('AMPHIBIAN_GENERATORS_SQLSVR', AMPHIBIAN_GENERATORS . 'SQLSVR'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_GENERATORS_SQLSVR_INTERFACES', AMPHIBIAN_GENERATORS_SQLSVR . 'interfaces'.DIRECTORY_SEPARATOR);
//User Projects
DEFINE('AMPHIBIAN_PROJECT', AMPHIBIAN . 'project'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_PROJECT_CURRENT', AMPHIBIAN_PROJECT . $currentProject . DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_PROJECT_CONFIG', AMPHIBIAN_PROJECT_CURRENT . 'config'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_PROJECT_CONFIG_PRODUCTION', AMPHIBIAN_PROJECT_CONFIG . 'production'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_PROJECT_CONFIG_STAGING', AMPHIBIAN_PROJECT_CONFIG . 'staging'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_PROJECT_DATABASE', AMPHIBIAN_PROJECT_CURRENT . 'database'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_PROJECT_DATABASE_PRODUCTION', AMPHIBIAN_PROJECT_DATABASE . 'production'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_PROJECT_DATABASE_STAGING', AMPHIBIAN_PROJECT_DATABASE . 'staging'.DIRECTORY_SEPARATOR);

//Specs
DEFINE('AMPHIBIAN_SPEC', AMPHIBIAN . 'spec'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_SPEC_CORE', AMPHIBIAN_SPEC . 'core'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_SPEC_GENERATORS', AMPHIBIAN_SPEC . 'generators'.DIRECTORY_SEPARATOR);
//Tests
DEFINE('AMPHIBIAN_TESTS', AMPHIBIAN . 'tests'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_TESTS_ACCEPTANCE', AMPHIBIAN_TESTS . 'acceptance' . DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_TESTS_ACCEPTANCE_CORE', AMPHIBIAN_TESTS_ACCEPTANCE . 'core' . DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_TESTS_ACCEPTANCE_GENERATORS', AMPHIBIAN_TESTS_ACCEPTANCE . 'generators' . DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_TESTS_INTEGRATION', AMPHIBIAN_TESTS . 'integration' . DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_TESTS_INTEGRATION_CORE', AMPHIBIAN_TESTS_INTEGRATION . 'core'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_TESTS_INTEGRATION_GENERATORS', AMPHIBIAN_TESTS_INTEGRATION . 'generators'.DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_TESTS_UNIT', AMPHIBIAN_TESTS . 'unit' . DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_TESTS_UNIT_CORE', AMPHIBIAN_TESTS_UNIT . 'core' . DIRECTORY_SEPARATOR);
DEFINE('AMPHIBIAN_TESTS_UNIT_GENERATORS', AMPHIBIAN_TESTS_UNIT . 'generators' . DIRECTORY_SEPARATOR);

define('AMPHIBIAN_LOG', AMPHIBIAN . 'log/');
define('AMPHIBIAN_SYSTEM_LOG', AMPHIBIAN_LOG . 'system/');
define('AMPHIBIAN_ACCESS_LOG', AMPHIBIAN_SYSTEM_LOG . 'access/');
define('AMPHIBIAN_EMAIL_LOG', AMPHIBIAN_SYSTEM_LOG . 'email/');
define('AMPHIBIAN_ERROR_LOG', AMPHIBIAN_SYSTEM_LOG . 'error/');
define('AMPHIBIAN_MALICIOUS_LOG', AMPHIBIAN_SYSTEM_LOG . 'malicious/');
define('AMPHIBIAN_SLOW_LOG', AMPHIBIAN_SYSTEM_LOG . 'slow/');
define('AMPHIBIAN_VIRUS_LOG', AMPHIBIAN_SYSTEM_LOG . 'virus/');
define('AMPHIBIAN_WARNING_LOG', AMPHIBIAN_SYSTEM_LOG . 'warning/');
define('AMPHIBIAN_DATABASE_LOG', AMPHIBIAN_LOG . 'database/');
define('AMPHIBIAN_DATABASE_BACKUP_LOG', AMPHIBIAN_DATABASE_LOG . 'backup/');
define('AMPHIBIAN_DATABASE_ERROR_LOG', AMPHIBIAN_DATABASE_LOG . 'error/');
define('AMPHIBIAN_DATABASE_QUERY_LOG', AMPHIBIAN_DATABASE_LOG . 'query/');
define('AMPHIBIAN_DATABASE_WARNING_LOG', AMPHIBIAN_DATABASE_LOG . 'warning/');


//Our Exception Handler
require_once AMPHIBIAN_CORE_NEUTRAL . "ExceptionHandler.php";
//set_exception_handler(array('ExceptionHandler','instance'));