<?php
require_once __DIR__ . DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."config/config.inc.php";
require_once AMPHIBIAN_CORE."basicView.php";
require_once __DIR__.DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."baseTest.php";
/**
 * Class basicViewTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/basicViewTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 17:05:32.
 *
 */
class basicViewTest 
	extends BaseTest
{
    /**
     * @var object basicView an instance of basicView
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new basicView();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSetViewCustomBrowse
     *
     * @covers basicView::setViewCustomBrowse
     *
     * @todo   Implement testSetViewCustomBrowse().
     *
     * @return void
     */
    public function testSetViewCustomBrowse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetViewCustomForm
     *
     * @covers basicView::setViewCustomForm
     *
     * @todo   Implement testSetViewCustomForm().
     *
     * @return void
     */
    public function testSetViewCustomForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetViewCustomPartials
     *
     * @covers basicView::setViewCustomPartials
     *
     * @todo   Implement testSetViewCustomPartials().
     *
     * @return void
     */
    public function testSetViewCustomPartials()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers basicView::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetViewGeneratedBrowse
     *
     * @covers basicView::setViewGeneratedBrowse
     *
     * @todo   Implement testSetViewGeneratedBrowse().
     *
     * @return void
     */
    public function testSetViewGeneratedBrowse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetViewGeneratedForm
     *
     * @covers basicView::setViewGeneratedForm
     *
     * @todo   Implement testSetViewGeneratedForm().
     *
     * @return void
     */
    public function testSetViewGeneratedForm()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetViewGeneratedPartials
     *
     * @covers basicView::setViewGeneratedPartials
     *
     * @todo   Implement testSetViewGeneratedPartials().
     *
     * @return void
     */
    public function testSetViewGeneratedPartials()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetSelectedValues
     *
     * @covers basicView::setSelectedValues
     *
     * @todo   Implement testSetSelectedValues().
     *
     * @return void
     */
    public function testSetSelectedValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetSelectedValues
     *
     * @covers basicView::getSelectedValues
     *
     * @todo   Implement testGetSelectedValues().
     *
     * @return void
     */
    public function testGetSelectedValues()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testRender
     *
     * @covers basicView::render
     *
     * @todo   Implement testRender().
     *
     * @return void
     */
    public function testRender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testRenderPartial
     *
     * @covers basicView::renderPartial
     *
     * @todo   Implement testRenderPartial().
     *
     * @return void
     */
    public function testRenderPartial()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
