<?php
require_once __DIR__ . DIRECTORY_SEPARATOR .  ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE."basicPage.php";

/**
 * Class basicPageTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/basicPageTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-24 at 16:12:39.
 *
 */
class basicPageTest 
	extends BaseTest
{
    /**
     * @var object basicPage an instance of basicPage
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new basicPage();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSetAgencies
     *
     * @covers basicPage::setAgencies
     *
     * @todo   Implement testSetAgencies().
     *
     * @return void
     */
    public function testSetAgencies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetAgencies
     *
     * @covers basicPage::getAgencies
     *
     * @todo   Implement testGetAgencies().
     *
     * @return void
     */
    public function testGetAgencies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetAuthor
     *
     * @covers basicPage::setAuthor
     *
     * @todo   Implement testSetAuthor().
     *
     * @return void
     */
    public function testSetAuthor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetAuthor
     *
     * @covers basicPage::getAuthor
     *
     * @todo   Implement testGetAuthor().
     *
     * @return void
     */
    public function testGetAuthor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetBrowserCheck
     *
     * @covers basicPage::setBrowserCheck
     *
     * @todo   Implement testSetBrowserCheck().
     *
     * @return void
     */
    public function testSetBrowserCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetBrowserCheck
     *
     * @covers basicPage::getBrowserCheck
     *
     * @todo   Implement testGetBrowserCheck().
     *
     * @return void
     */
    public function testGetBrowserCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetContent
     *
     * @covers basicPage::setContent
     *
     * @todo   Implement testSetContent().
     *
     * @return void
     */
    public function testSetContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetContent
     *
     * @covers basicPage::getContent
     *
     * @todo   Implement testGetContent().
     *
     * @return void
     */
    public function testGetContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetController
     *
     * @covers basicPage::setController
     *
     * @todo   Implement testSetController().
     *
     * @return void
     */
    public function testSetController()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetController
     *
     * @covers basicPage::getController
     *
     * @todo   Implement testGetController().
     *
     * @return void
     */
    public function testGetController()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetCss
     *
     * @covers basicPage::setCss
     *
     * @todo   Implement testSetCss().
     *
     * @return void
     */
    public function testSetCss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetCss
     *
     * @covers basicPage::getCss
     *
     * @todo   Implement testGetCss().
     *
     * @return void
     */
    public function testGetCss()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetDescription
     *
     * @covers basicPage::setDescription
     *
     * @todo   Implement testSetDescription().
     *
     * @return void
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetDescription
     *
     * @covers basicPage::getDescription
     *
     * @todo   Implement testGetDescription().
     *
     * @return void
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetDnsPrefetch
     *
     * @covers basicPage::setDnsPrefetch
     *
     * @todo   Implement testSetDnsPrefetch().
     *
     * @return void
     */
    public function testSetDnsPrefetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetDnsPrefetch
     *
     * @covers basicPage::getDnsPrefetch
     *
     * @todo   Implement testGetDnsPrefetch().
     *
     * @return void
     */
    public function testGetDnsPrefetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetEncoding
     *
     * @covers basicPage::setEncoding
     *
     * @todo   Implement testSetEncoding().
     *
     * @return void
     */
    public function testSetEncoding()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetEncoding
     *
     * @covers basicPage::getEncoding
     *
     * @todo   Implement testGetEncoding().
     *
     * @return void
     */
    public function testGetEncoding()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetFavicon
     *
     * @covers basicPage::setFavicon
     *
     * @todo   Implement testSetFavicon().
     *
     * @return void
     */
    public function testSetFavicon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetFavicon
     *
     * @covers basicPage::getFavicon
     *
     * @todo   Implement testGetFavicon().
     *
     * @return void
     */
    public function testGetFavicon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetFooter
     *
     * @covers basicPage::setFooter
     *
     * @todo   Implement testSetFooter().
     *
     * @return void
     */
    public function testSetFooter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetFooter
     *
     * @covers basicPage::getFooter
     *
     * @todo   Implement testGetFooter().
     *
     * @return void
     */
    public function testGetFooter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetHeader
     *
     * @covers basicPage::setHeader
     *
     * @todo   Implement testSetHeader().
     *
     * @return void
     */
    public function testSetHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetHeader
     *
     * @covers basicPage::getHeader
     *
     * @todo   Implement testGetHeader().
     *
     * @return void
     */
    public function testGetHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetInclude
     *
     * @covers basicPage::setInclude
     *
     * @todo   Implement testSetInclude().
     *
     * @return void
     */
    public function testSetInclude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetInclude
     *
     * @covers basicPage::getInclude
     *
     * @todo   Implement testGetInclude().
     *
     * @return void
     */
    public function testGetInclude()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetJQuery
     *
     * @covers basicPage::setJQuery
     *
     * @todo   Implement testSetJQuery().
     *
     * @return void
     */
    public function testSetJQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetJQuery
     *
     * @covers basicPage::getJQuery
     *
     * @todo   Implement testGetJQuery().
     *
     * @return void
     */
    public function testGetJQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetJQueryMobile
     *
     * @covers basicPage::setJQueryMobile
     *
     * @todo   Implement testSetJQueryMobile().
     *
     * @return void
     */
    public function testSetJQueryMobile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetJQueryMobile
     *
     * @covers basicPage::getJQueryMobile
     *
     * @todo   Implement testGetJQueryMobile().
     *
     * @return void
     */
    public function testGetJQueryMobile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetJQueryUI
     *
     * @covers basicPage::setJQueryUI
     *
     * @todo   Implement testSetJQueryUI().
     *
     * @return void
     */
    public function testSetJQueryUI()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetJQueryUI
     *
     * @covers basicPage::getJQueryUI
     *
     * @todo   Implement testGetJQueryUI().
     *
     * @return void
     */
    public function testGetJQueryUI()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetJs
     *
     * @covers basicPage::setJs
     *
     * @todo   Implement testSetJs().
     *
     * @return void
     */
    public function testSetJs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetJs
     *
     * @covers basicPage::getJs
     *
     * @todo   Implement testGetJs().
     *
     * @return void
     */
    public function testGetJs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetKeywords
     *
     * @covers basicPage::setKeywords
     *
     * @todo   Implement testSetKeywords().
     *
     * @return void
     */
    public function testSetKeywords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetKeywords
     *
     * @covers basicPage::getKeywords
     *
     * @todo   Implement testGetKeywords().
     *
     * @return void
     */
    public function testGetKeywords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetKeywordsNot
     *
     * @covers basicPage::setKeywordsNot
     *
     * @todo   Implement testSetKeywordsNot().
     *
     * @return void
     */
    public function testSetKeywordsNot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetKeywordsNot
     *
     * @covers basicPage::getKeywordsNot
     *
     * @todo   Implement testGetKeywordsNot().
     *
     * @return void
     */
    public function testGetKeywordsNot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetLanguage
     *
     * @covers basicPage::setLanguage
     *
     * @todo   Implement testSetLanguage().
     *
     * @return void
     */
    public function testSetLanguage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetLanguage
     *
     * @covers basicPage::getLanguage
     *
     * @todo   Implement testGetLanguage().
     *
     * @return void
     */
    public function testGetLanguage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetLoad
     *
     * @covers basicPage::setLoad
     *
     * @todo   Implement testSetLoad().
     *
     * @return void
     */
    public function testSetLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetLoad
     *
     * @covers basicPage::getLoad
     *
     * @todo   Implement testGetLoad().
     *
     * @return void
     */
    public function testGetLoad()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetModels
     *
     * @covers basicPage::setModels
     *
     * @todo   Implement testSetModels().
     *
     * @return void
     */
    public function testSetModels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetModels
     *
     * @covers basicPage::getModels
     *
     * @todo   Implement testGetModels().
     *
     * @return void
     */
    public function testGetModels()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetModernizr
     *
     * @covers basicPage::setModernizr
     *
     * @todo   Implement testSetModernizr().
     *
     * @return void
     */
    public function testSetModernizr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetModernizr
     *
     * @covers basicPage::getModernizr
     *
     * @todo   Implement testGetModernizr().
     *
     * @return void
     */
    public function testGetModernizr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetPngFix
     *
     * @covers basicPage::setPngFix
     *
     * @todo   Implement testSetPngFix().
     *
     * @return void
     */
    public function testSetPngFix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetPngFix
     *
     * @covers basicPage::getPngFix
     *
     * @todo   Implement testGetPngFix().
     *
     * @return void
     */
    public function testGetPngFix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetPrefetch
     *
     * @covers basicPage::setPrefetch
     *
     * @todo   Implement testSetPrefetch().
     *
     * @return void
     */
    public function testSetPrefetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetPrefetch
     *
     * @covers basicPage::getPrefetch
     *
     * @todo   Implement testGetPrefetch().
     *
     * @return void
     */
    public function testGetPrefetch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetPrerender
     *
     * @covers basicPage::setPrerender
     *
     * @todo   Implement testSetPrerender().
     *
     * @return void
     */
    public function testSetPrerender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetPrerender
     *
     * @covers basicPage::getPrerender
     *
     * @todo   Implement testGetPrerender().
     *
     * @return void
     */
    public function testGetPrerender()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetRequired
     *
     * @covers basicPage::setRequired
     *
     * @todo   Implement testSetRequired().
     *
     * @return void
     */
    public function testSetRequired()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetRequired
     *
     * @covers basicPage::getRequired
     *
     * @todo   Implement testGetRequired().
     *
     * @return void
     */
    public function testGetRequired()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetRobots
     *
     * @covers basicPage::setRobots
     *
     * @todo   Implement testSetRobots().
     *
     * @return void
     */
    public function testSetRobots()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetRobots
     *
     * @covers basicPage::getRobots
     *
     * @todo   Implement testGetRobots().
     *
     * @return void
     */
    public function testGetRobots()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetTitle
     *
     * @covers basicPage::setTitle
     *
     * @todo   Implement testSetTitle().
     *
     * @return void
     */
    public function testSetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetTitle
     *
     * @covers basicPage::getTitle
     *
     * @todo   Implement testGetTitle().
     *
     * @return void
     */
    public function testGetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetViewport
     *
     * @covers basicPage::setViewport
     *
     * @todo   Implement testSetViewport().
     *
     * @return void
     */
    public function testSetViewport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetViewport
     *
     * @covers basicPage::getViewport
     *
     * @todo   Implement testGetViewport().
     *
     * @return void
     */
    public function testGetViewport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetViews
     *
     * @covers basicPage::setViews
     *
     * @todo   Implement testSetViews().
     *
     * @return void
     */
    public function testSetViews()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetViews
     *
     * @covers basicPage::getViews
     *
     * @todo   Implement testGetViews().
     *
     * @return void
     */
    public function testGetViews()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testOnAction
     *
     * @covers basicPage::onAction
     *
     * @todo   Implement testOnAction().
     *
     * @return void
     */
    public function testOnAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
