<?php
require_once __DIR__ . DIRECTORY_SEPARATOR .  ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE_MYSQLI . "CheckBoxQueryMySQLi.php";
/**
 * Class checkBoxQueryTest
 *
 * @category Test
 * @package  CheckBoxQuery
 * @author   Carl 'Tex' Morgan <texmorgan@amphibian.co>
 * @license  All rights reserved by Inselberge Inc. unless otherwise stated.
 * @link     documentation/checkBoxQueryTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 17:05:32.
 *
 */
class CheckBoxQueryMySQLiTest
    extends BaseTest
{
    /**
     * @var object checkBoxQuery an instance of checkBoxQuery
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = CheckBoxQueryMySQLi::instance($databaseConnection);
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSetIdField
     *
     * @covers checkBoxQuery::setIdField
     *
     * @return void
     */
    public function testSetIdField()
    {
        $this->expected = true;
        $this->actual = $this->object->setIdField("first_name");
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testExecute
     *
     * @covers checkBoxQuery::execute
     *
     * @return void
     */
    public function testExecute()
    {
        $this->expected = true;
        $this->actual = $this->object->execute();
        $this->assertEquals($this->expected, $this->actual);

    }
}
