<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".."  . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE."databaseConnectionFactory.php";

/**
 * Class databaseConnectionFactoryTest
 *
 * @category Test
 * @package  DatabaseConnection
 * @author   Carl 'Tex' Morgan <texmorgan@amphibian.co>
 * @license  All rights reserved by Inselberge Inc. unless otherwise stated.
 * @link     documentation/DatabaseConnectionFactoryTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 17:05:32.
 *
 */
class DatabaseConnectionFactoryTest
    extends BaseTest
{
    /**
     * @var object DatabaseConnectionFactory an instance of DatabaseConnectionFactory
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {

    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testConnect
     *
     * @covers DatabaseConnectionFactory::connect
     *
     * @todo   Implement testConnect().
     *
     * @return void
     */
    public function testConnect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
