<?php

require_once __DIR__ . DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR.".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "config" . DIRECTORY_SEPARATOR . "config.inc.php";
require_once __DIR__ . DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."baseTest.php";
require_once AMPHIBIAN_CORE . "Parameter.php";
/**
 * Class parameterTest
 *
 * @category Test
 * @package  Core
 * @author   Carl "Tex" Morgan <texmorgan@amphibian.co>
 * @license  All rights reserved by Inselberge Inc. unless otherwise stated.
 * @link     http://amphibian.co/documentation/parameterTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-17 at 13:41:29.
 */
class parameterTest 
    extends BaseTest
{
    /**
     * @var object parameter an instance of parameter
     */
    protected $object;
    /**
     * @var mixed expected The expected result
     */
    protected $expected;
    /**
     * @var mixed actual The actual result
     */
    protected $actual;
    /**
     * @var mixed arguments arguments to provide to a test
     */
    protected $arguments;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = Parameter::instance("http://somewebsite.com/Geekdom/user/browse/groupBy/create_date/de/modify_date/as/limit/25/offset/25");
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
        unset($this->object);
    }

    /** testInstance
     *
     * @covers Parameter::instance
     *
     * @return void
     */
    public function testInstance()
    {
        $this->arguments = "Geekdom/user/browse/groupBy/create_date/de/modify_date/as/limit/25/offset/25";
        $this->expected = $this->object;
        $this->actual = Parameter::instance($this->arguments);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testExecute
     *
     * @covers Parameter::execute
     *
     * @return void
     */
    public function testExecute()
    {
        $this->expected = true;
        $this->actual = $this->object->execute();
        $this->assertEquals($this->expected, $this->actual);
    }

    /** setVariablesDataProvider
     *
     * @return array
     */
    public function setVariablesDataProvider()
    {
        return array(
            "id"=>"587",
            "first_name"=>"Tex",
            "last_name"=>"Morgan",
            "action"=>"get",
            "branch"=>"Geekdom",
            "controller"=>"user"
        );
    }

    /** testSetVariables
     *
     * @param array $vars the variables to set
     *
     * @dataProvider setVariablesDataProvider
     *
     * @covers Parameter::setVariables
     *
     * @return void
     */
    public function testSetVariables( array $vars )
    {
        $this->arguments=$vars;
        $this->expected = true;
        $this->actual = $this->object->setVariables($this->arguments);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testGetVariables
     *
     * @covers Parameter::getVariables
     *
     * @return void
     */
    public function testGetVariables()
    {
        $this->expected = $this->setVariablesDataProvider();
        $this->object->setVariables($this->setVariablesDataProvider());
        $this->actual = $this->object->getVariables();
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testGetSpecificVariable
     *
     * @param string $key   the index of the variable
     * @param mixed  $value the expected value
     *
     * @covers Parameter::getSpecificVariable
     *
     * @return void
     */
    public function testGetSpecificVariable($key, $value)
    {
        $this->expected = $value;
        $this->arguments = $key;
        $this->actual = $this->object->getSpecificVariable($this->arguments);
        $this->assertEquals($this->expected, $this->actual);
    }

    public function specificDataProvider()
    {
        return array(
          array("where", "first_name lk 'Te'"),
          array("having", "status eq 'enabled'"),
          array("orderBy", "id as")
        );
    }

    /** testSetSpecificVariable
     *
     * @param string $key   the index of the variable
     * @param mixed  $value the value to append to the key
     *
     * @dataProvider specificDataProvider
     *
     * @covers Parameter::setSpecificVariable
     *
     * @return void
     */
    public function testSetSpecificVariable($key, $value)
    {
        $this->expected=true;
        $this->actual= $this->object->setSpecificVariable($key, $value);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testAppendSpecificVariable
     *
     * @param string $key   the index of the variable
     * @param mixed  $value the value to append to the key
     *
     * @dataProvider specificDataProvider
     *
     * @covers Parameter::appendSpecificVariable
     *
     * @return void
     */
    public function testAppendSpecificVariable($key, $value)
    {
        $this->expected = true;
        $this->actual = $this->object->appendSpecificVariable($key, $value);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testGetDataVariables
     *
     * @covers Parameter::getDataVariables
     *
     * @return void
     */
    public function testGetDataVariables()
    {
        $this->expected = $this->setVariablesDataProvider();
        $this->object->setVariables($this->setVariablesDataProvider());
        $this->actual = $this->object->getDataVariables();
        $this->assertEquals($this->expected, $this->actual);
    }
}
