<?php

require_once __DIR__ . DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."config".DIRECTORY_SEPARATOR."config.inc.php";
require_once AMPHIBIAN_TESTS . "baseTest.php";
require_once AMPHIBIAN_CORE_NEUTRAL."Session.php";
/**
 * Class SessionTest
 *
 * @category Test
 * @package  Session
 * @author   Carl 'Tex' Morgan <texmorgan@amphibian.co>
 * @license  All rights reserved by Inselberge Inc. unless otherwise stated.
 * @link     documentation/SessionTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 17:05:30.
 *
 */
class SessionTest 
    extends BaseTest
{

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = Session::instance();
    }

    /** testInstance
     *
     * @covers Session::instance
     *
     * @return void
     */
    public function testInstance()
    {
        $this->expected = $this->object;
        $this->actual = Session::instance();
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testGet
     *
     * @covers Session::get
     *
     * @return void
     */
    public function testGet()
    {
        $this->expected = array();
        $this->actual = $this->object->get(
            "aNameSpace",
            array("firstName"=>"Robert", "lastName"=>"Paulsen")
        );
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testSet
     *
     * @covers Session::set
     *
     * @return void
     */
    public function testSet()
    {
        $this->expected = true;
        $this->actual = $this->object->set(
            "aNameSpace",
            array("firstName"=>"Robert", "lastName"=>"Paulsen")
        );
        $this->assertEquals($this->expected, $this->actual);
    }
}
