<?php
require_once __DIR__ . DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR.".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "config" . DIRECTORY_SEPARATOR . "config.inc.php";
require_once __DIR__ . DIRECTORY_SEPARATOR."..".DIRECTORY_SEPARATOR."baseTest.php";
require_once AMPHIBIAN_CORE."TableBuilderMySQLi.php";
/**
 * Class TableBuilderTest
 *
 * @category Test
 * @package  TableBuilder
 * @author   Carl 'Tex' Morgan <texmorgan@amphibian.co>
 * @license  
 * @link     documentation/TableBuilderTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 17:05:30.
 *
 */
class TableBuilderTest 
    extends BaseTest
{
    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = TableBuilderMySQLi::instance("testTable");
    }

    /** testSetOption
     *
     * @covers TableBuilder::setOption
     *
     * @todo   Implement testSetOption().
     *
     * @return void
     */
    public function testSetOption()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintHead
     *
     * @covers TableBuilder::printHead
     *
     * @todo   Implement testPrintHead().
     *
     * @return void
     */
    public function testPrintHead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintBody
     *
     * @covers TableBuilder::printBody
     *
     * @todo   Implement testPrintBody().
     *
     * @return void
     */
    public function testPrintBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintFoot
     *
     * @covers TableBuilder::printFoot
     *
     * @todo   Implement testPrintFoot().
     *
     * @return void
     */
    public function testPrintFoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintStartTable
     *
     * @covers TableBuilder::printStartTable
     *
     * @todo   Implement testPrintStartTable().
     *
     * @return void
     */
    public function testPrintStartTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintEndTable
     *
     * @covers TableBuilder::printEndTable
     *
     * @todo   Implement testPrintEndTable().
     *
     * @return void
     */
    public function testPrintEndTable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintStartBody
     *
     * @covers TableBuilder::printStartBody
     *
     * @todo   Implement testPrintStartBody().
     *
     * @return void
     */
    public function testPrintStartBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintEndBody
     *
     * @covers TableBuilder::printEndBody
     *
     * @todo   Implement testPrintEndBody().
     *
     * @return void
     */
    public function testPrintEndBody()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintPager
     *
     * @covers TableBuilder::printPager
     *
     * @todo   Implement testPrintPager().
     *
     * @return void
     */
    public function testPrintPager()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintScripts
     *
     * @covers TableBuilder::printScripts
     *
     * @todo   Implement testPrintScripts().
     *
     * @return void
     */
    public function testPrintScripts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintCSS
     *
     * @covers TableBuilder::printCSS
     *
     * @todo   Implement testPrintCSS().
     *
     * @return void
     */
    public function testPrintCSS()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers TableBuilder::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecuteFromPayload
     *
     * @covers TableBuilder::executeFromPayload
     *
     * @todo   Implement testExecuteFromPayload().
     *
     * @return void
     */
    public function testExecuteFromPayload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetSpecific
     *
     * @covers TableBuilder::setSpecific
     *
     * @todo   Implement testSetSpecific().
     *
     * @return void
     */
    public function testSetSpecific()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
