<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE_NEUTRAL."APIRequest.php";
/**
 * Class APIRequestTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/APIRequestTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 23:04:26.
 *
 */
class APIRequestTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object APIRequest an instance of APIRequest
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new APIRequest();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers APIRequest::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testFactory
     *
     * @covers APIRequest::factory
     *
     * @todo   Implement testFactory().
     *
     * @return void
     */
    public function testFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetAction
     *
     * @covers APIRequest::setAction
     *
     * @todo   Implement testSetAction().
     *
     * @return void
     */
    public function testSetAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetAction
     *
     * @covers APIRequest::getAction
     *
     * @todo   Implement testGetAction().
     *
     * @return void
     */
    public function testGetAction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetApplication
     *
     * @covers APIRequest::setApplication
     *
     * @todo   Implement testSetApplication().
     *
     * @return void
     */
    public function testSetApplication()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetApplication
     *
     * @covers APIRequest::getApplication
     *
     * @todo   Implement testGetApplication().
     *
     * @return void
     */
    public function testGetApplication()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetArguments
     *
     * @covers APIRequest::setArguments
     *
     * @todo   Implement testSetArguments().
     *
     * @return void
     */
    public function testSetArguments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetArguments
     *
     * @covers APIRequest::getArguments
     *
     * @todo   Implement testGetArguments().
     *
     * @return void
     */
    public function testGetArguments()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetBranch
     *
     * @covers APIRequest::setBranch
     *
     * @todo   Implement testSetBranch().
     *
     * @return void
     */
    public function testSetBranch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetBranch
     *
     * @covers APIRequest::getBranch
     *
     * @todo   Implement testGetBranch().
     *
     * @return void
     */
    public function testGetBranch()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetKey
     *
     * @covers APIRequest::setKey
     *
     * @todo   Implement testSetKey().
     *
     * @return void
     */
    public function testSetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetKey
     *
     * @covers APIRequest::getKey
     *
     * @todo   Implement testGetKey().
     *
     * @return void
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetType
     *
     * @covers APIRequest::setType
     *
     * @todo   Implement testSetType().
     *
     * @return void
     */
    public function testSetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetType
     *
     * @covers APIRequest::getType
     *
     * @todo   Implement testGetType().
     *
     * @return void
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetTimestamp
     *
     * @covers APIRequest::setTimestamp
     *
     * @todo   Implement testSetTimestamp().
     *
     * @return void
     */
    public function testSetTimestamp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetTimestamp
     *
     * @covers APIRequest::getTimestamp
     *
     * @todo   Implement testGetTimestamp().
     *
     * @return void
     */
    public function testGetTimestamp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
