<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE."APIResponse.php";
/**
 * Class APIResponseTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/APIResponseTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 23:04:48.
 *
 */
class APIResponseTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object APIResponse an instance of APIResponse
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new APIResponse();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers APIResponse::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testFactory
     *
     * @covers APIResponse::factory
     *
     * @todo   Implement testFactory().
     *
     * @return void
     */
    public function testFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetApplication
     *
     * @covers APIResponse::setApplication
     *
     * @todo   Implement testSetApplication().
     *
     * @return void
     */
    public function testSetApplication()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetApplication
     *
     * @covers APIResponse::getApplication
     *
     * @todo   Implement testGetApplication().
     *
     * @return void
     */
    public function testGetApplication()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetKey
     *
     * @covers APIResponse::setKey
     *
     * @todo   Implement testSetKey().
     *
     * @return void
     */
    public function testSetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetKey
     *
     * @covers APIResponse::getKey
     *
     * @todo   Implement testGetKey().
     *
     * @return void
     */
    public function testGetKey()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetPageSize
     *
     * @covers APIResponse::setPageSize
     *
     * @todo   Implement testSetPageSize().
     *
     * @return void
     */
    public function testSetPageSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetPageSize
     *
     * @covers APIResponse::getPageSize
     *
     * @todo   Implement testGetPageSize().
     *
     * @return void
     */
    public function testGetPageSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetPayload
     *
     * @covers APIResponse::setPayload
     *
     * @todo   Implement testSetPayload().
     *
     * @return void
     */
    public function testSetPayload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testAppendPayload
     *
     * @covers APIResponse::appendPayload
     *
     * @todo   Implement testAppendPayload().
     *
     * @return void
     */
    public function testAppendPayload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetPayload
     *
     * @covers APIResponse::getPayload
     *
     * @todo   Implement testGetPayload().
     *
     * @return void
     */
    public function testGetPayload()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetPayloadSize
     *
     * @covers APIResponse::setPayloadSize
     *
     * @todo   Implement testSetPayloadSize().
     *
     * @return void
     */
    public function testSetPayloadSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetPayloadSize
     *
     * @covers APIResponse::getPayloadSize
     *
     * @todo   Implement testGetPayloadSize().
     *
     * @return void
     */
    public function testGetPayloadSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetSuccess
     *
     * @covers APIResponse::setSuccess
     *
     * @todo   Implement testSetSuccess().
     *
     * @return void
     */
    public function testSetSuccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetSuccess
     *
     * @covers APIResponse::getSuccess
     *
     * @todo   Implement testGetSuccess().
     *
     * @return void
     */
    public function testGetSuccess()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetTimestamp
     *
     * @covers APIResponse::setTimestamp
     *
     * @todo   Implement testSetTimestamp().
     *
     * @return void
     */
    public function testSetTimestamp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetTimestamp
     *
     * @covers APIResponse::getTimestamp
     *
     * @todo   Implement testGetTimestamp().
     *
     * @return void
     */
    public function testGetTimestamp()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetType
     *
     * @covers APIResponse::setType
     *
     * @todo   Implement testSetType().
     *
     * @return void
     */
    public function testSetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetType
     *
     * @covers APIResponse::getType
     *
     * @todo   Implement testGetType().
     *
     * @return void
     */
    public function testGetType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers APIResponse::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
