<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE."File.php";
/**
 * Class FileTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/FileTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 23:06:35.
 *
 */
class FileTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object File an instance of File
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new File();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSetName
     *
     * @covers File::setName
     *
     * @todo   Implement testSetName().
     *
     * @return void
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testCascade
     *
     * @covers File::cascade
     *
     * @todo   Implement testCascade().
     *
     * @return void
     */
    public function testCascade()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testCopy
     *
     * @covers File::copy
     *
     * @todo   Implement testCopy().
     *
     * @return void
     */
    public function testCopy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testRename
     *
     * @covers File::rename
     *
     * @todo   Implement testRename().
     *
     * @return void
     */
    public function testRename()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testDelete
     *
     * @covers File::delete
     *
     * @todo   Implement testDelete().
     *
     * @return void
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testChangeOwner
     *
     * @covers File::changeOwner
     *
     * @todo   Implement testChangeOwner().
     *
     * @return void
     */
    public function testChangeOwner()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testChangeGroup
     *
     * @covers File::changeGroup
     *
     * @todo   Implement testChangeGroup().
     *
     * @return void
     */
    public function testChangeGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testChangePermissions
     *
     * @covers File::changePermissions
     *
     * @todo   Implement testChangePermissions().
     *
     * @return void
     */
    public function testChangePermissions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintAccessTime
     *
     * @covers File::printAccessTime
     *
     * @todo   Implement testPrintAccessTime().
     *
     * @return void
     */
    public function testPrintAccessTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintChangeTime
     *
     * @covers File::printChangeTime
     *
     * @todo   Implement testPrintChangeTime().
     *
     * @return void
     */
    public function testPrintChangeTime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintFileGroup
     *
     * @covers File::printFileGroup
     *
     * @todo   Implement testPrintFileGroup().
     *
     * @return void
     */
    public function testPrintFileGroup()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintFileOwner
     *
     * @covers File::printFileOwner
     *
     * @todo   Implement testPrintFileOwner().
     *
     * @return void
     */
    public function testPrintFileOwner()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintFilePermissions
     *
     * @covers File::printFilePermissions
     *
     * @todo   Implement testPrintFilePermissions().
     *
     * @return void
     */
    public function testPrintFilePermissions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintFileSize
     *
     * @covers File::printFileSize
     *
     * @todo   Implement testPrintFileSize().
     *
     * @return void
     */
    public function testPrintFileSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintFileType
     *
     * @covers File::printFileType
     *
     * @todo   Implement testPrintFileType().
     *
     * @return void
     */
    public function testPrintFileType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintDirectoryName
     *
     * @covers File::printDirectoryName
     *
     * @todo   Implement testPrintDirectoryName().
     *
     * @return void
     */
    public function testPrintDirectoryName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintBaseName
     *
     * @covers File::printBaseName
     *
     * @todo   Implement testPrintBaseName().
     *
     * @return void
     */
    public function testPrintBaseName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintExtension
     *
     * @covers File::printExtension
     *
     * @todo   Implement testPrintExtension().
     *
     * @return void
     */
    public function testPrintExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintFileName
     *
     * @covers File::printFileName
     *
     * @todo   Implement testPrintFileName().
     *
     * @return void
     */
    public function testPrintFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
