<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "config" . DIRECTORY_SEPARATOR . "config.inc.php";
require_once AMPHIBIAN_CORE_NEUTRAL."Serialize.php";
/**
 * Class SerializeTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/SerializeTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 23:08:10.
 *
 */
class SerializeTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object Serialize an instance of Serialize
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new Serialize();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers Serialize::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetDirection
     *
     * @covers Serialize::setDirection
     *
     * @todo   Implement testSetDirection().
     *
     * @return void
     */
    public function testSetDirection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetDirection
     *
     * @covers Serialize::getDirection
     *
     * @todo   Implement testGetDirection().
     *
     * @return void
     */
    public function testGetDirection()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetData
     *
     * @covers Serialize::setData
     *
     * @todo   Implement testSetData().
     *
     * @return void
     */
    public function testSetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testAppendData
     *
     * @covers Serialize::appendData
     *
     * @todo   Implement testAppendData().
     *
     * @return void
     */
    public function testAppendData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetData
     *
     * @covers Serialize::getData
     *
     * @todo   Implement testGetData().
     *
     * @return void
     */
    public function testGetData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers Serialize::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetOutput
     *
     * @covers Serialize::getOutput
     *
     * @todo   Implement testGetOutput().
     *
     * @return void
     */
    public function testGetOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
