<?php

require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE_NEUTRAL . "SessionException.php";
/**
 * Class sessionExceptionTest
 *
 * @category Test
 * @package  SessionException
 * @author   Carl 'Tex' Morgan <texmorgan@amphibian.co>
 * @license  All rights reserved by Inselberge Inc. unless otherwise stated.
 * @link     http://amphibian.co/documentation/sessionExceptionTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 17:05:30.
 *
 */
class sessionExceptionTest 
    extends BaseTest
{
    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new sessionException("An error occurred");
    }

    /** testConstruct
     *
     * @param $message
     * @param $expectedResult
     *
     * @covers SessionException::__construct
     *
     * @return void
     */
    public function testConstruct()
    {
        $this->expected = $this->object;
        $this->actual = new sessionException("An error occurred");
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testPrintMessage
     *
     * @covers sessionException::printMessage
     *
     * @return void
     */
    public function testPrintMessage()
    {
        $this->expected = null;
        $this->actual = $this->object->printMessage();
        $this->assertEquals($this->expected, $this->actual);
    }
}
