<?php

require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE_NEUTRAL."SuperGlobal.php";
/**
 * Class SuperGlobalTest
 *
 * @category Test
 * @package  Core
 * @author   Carl "Tex" Morgan <texmorgan@amphibian.co>
 * @license  All rights reserved by Inselberge Inc. unless otherwise stated.
 * @link     http://amphibian.co/documentation/SuperGlobalTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-09-08 at 17:05:30.
 *
 */
class SuperGlobalTest
    extends BaseTest
{

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new SuperGlobal($_SERVER);
    }

    /** testCheckEqual
     *
     * @covers SuperGlobal::checkEqual
     *
     * @return void
     */
    public function testCheckEqual()
    {
        $this->expected = true;
        $this->arguments = new SuperGlobal($_SERVER);
        $this->actual = $this->object->checkEqual($this->arguments);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testSetLocalArray
     *
     * @covers SuperGlobal::setLocalArray
     *
     * @return void
     */
    public function testSetLocalArray()
    {
        $this->expected = true;
        $this->arguments = $_SERVER;
        $this->actual = $this->object->setLocalArray($this->arguments);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testSetLocalArrayByKey
     *
     * @covers SuperGlobal::setLocalArrayByKey
     *
     * @return void
     */
    public function testSetLocalArrayByKey()
    {
        $this->expected = true;
        $this->actual = $this->object->setLocalArrayByKey("USER", "texmorgan");
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testGetLocalArray
     *
     * @covers SuperGlobal::getLocalArray
     *
     * @return void
     */
    public function testGetLocalArray()
    {
        $this->expected = $_SERVER;
        $this->object->setLocalArray($_SERVER);
        $this->actual = $this->object->getLocalArray();
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testGetLocalArrayByKey
     *
     * @covers SuperGlobal::getLocalArrayByKey
     *
     * @return void
     */
    public function testGetLocalArrayByKey()
    {
        $this->expected = "ubuntu";
        $this->arguments = "DESKTOP_SESSION";
        $this->object->setLocalArray($_SERVER);
        $this->actual= $this->object->getLocalArrayByKey($this->arguments);
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testPrintSize
     *
     * @covers SuperGlobal::printSize
     *
     * @return void
     */
    public function testPrintSize()
    {
        $this->expected = null;
        $this->actual = $this->object->printSize();
        $this->assertEquals($this->expected, $this->actual);
    }
}
