<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE_NEUTRAL."XML.php";
/**
 * Class XMLTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/XMLTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 23:09:03.
 *
 */
class XMLTest 
    extends PHPUnit_Framework_TestCase
{
    /**
     * @var object XML an instance of XML
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new XML();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers XML::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetReadOrWrite
     *
     * @covers XML::setReadOrWrite
     *
     * @todo   Implement testSetReadOrWrite().
     *
     * @return void
     */
    public function testSetReadOrWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetReadOrWrite
     *
     * @covers XML::getReadOrWrite
     *
     * @todo   Implement testGetReadOrWrite().
     *
     * @return void
     */
    public function testGetReadOrWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetFileHandle
     *
     * @covers XML::setFileHandle
     *
     * @todo   Implement testSetFileHandle().
     *
     * @return void
     */
    public function testSetFileHandle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetFileHandle
     *
     * @covers XML::getFileHandle
     *
     * @todo   Implement testGetFileHandle().
     *
     * @return void
     */
    public function testGetFileHandle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetCharset
     *
     * @covers XML::setCharset
     *
     * @todo   Implement testSetCharset().
     *
     * @return void
     */
    public function testSetCharset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetCharset
     *
     * @covers XML::getCharset
     *
     * @todo   Implement testGetCharset().
     *
     * @return void
     */
    public function testGetCharset()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetDataArray
     *
     * @covers XML::setDataArray
     *
     * @todo   Implement testSetDataArray().
     *
     * @return void
     */
    public function testSetDataArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetDataArray
     *
     * @covers XML::getDataArray
     *
     * @todo   Implement testGetDataArray().
     *
     * @return void
     */
    public function testGetDataArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetTableColumns
     *
     * @covers XML::setTableColumns
     *
     * @todo   Implement testSetTableColumns().
     *
     * @return void
     */
    public function testSetTableColumns()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetTableName
     *
     * @covers XML::setTableName
     *
     * @todo   Implement testSetTableName().
     *
     * @return void
     */
    public function testSetTableName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetBuffer
     *
     * @covers XML::getBuffer
     *
     * @todo   Implement testGetBuffer().
     *
     * @return void
     */
    public function testGetBuffer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetVersion
     *
     * @covers XML::setVersion
     *
     * @todo   Implement testSetVersion().
     *
     * @return void
     */
    public function testSetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetVersion
     *
     * @covers XML::getVersion
     *
     * @todo   Implement testGetVersion().
     *
     * @return void
     */
    public function testGetVersion()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers XML::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testWrite
     *
     * @covers XML::write
     *
     * @todo   Implement testWrite().
     *
     * @return void
     */
    public function testWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testPrintXML
     *
     * @covers XML::printXML
     *
     * @todo   Implement testPrintXML().
     *
     * @return void
     */
    public function testPrintXML()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testRead
     *
     * @covers XML::read
     *
     * @todo   Implement testRead().
     *
     * @return void
     */
    public function testRead()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testCheck
     *
     * @covers XML::check
     *
     * @todo   Implement testCheck().
     *
     * @return void
     */
    public function testCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testShow
     *
     * @covers XML::show
     *
     * @todo   Implement testShow().
     *
     * @return void
     */
    public function testShow()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
