<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";


require_once AMPHIBIAN_GENERATORS_NEUTRAL."CoreUpdate.php";
/**
 * Class CoreUpdateTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/CoreUpdateTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:56:31.
 *
 */
class CoreUpdateTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object CoreUpdate an instance of CoreUpdate
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new CoreUpdate();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers CoreUpdate::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testFactory
     *
     * @covers CoreUpdate::factory
     *
     * @todo   Implement testFactory().
     *
     * @return void
     */
    public function testFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetDestination
     *
     * @covers CoreUpdate::setDestination
     *
     * @todo   Implement testSetDestination().
     *
     * @return void
     */
    public function testSetDestination()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers CoreUpdate::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
