<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE."BasicModelMySQLi.php";
/**
 * Class BasicModelMySQLiTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/BasicModelMySQLiTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 22:56:02.
 *
 */
class BasicModelMySQLiTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object BasicModelMySQLi an instance of BasicModelMySQLi
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new BasicModelMySQLi();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }
}
