<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE."BasicFrontControllerMySQLi.php";
/**
 * Class BasicFrontControllerMySQLiTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/BasicFrontControllerMySQLiTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 22:55:36.
 *
 */
class BasicFrontControllerMySQLiTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object BasicFrontControllerMySQLi an instance of BasicFrontControllerMySQLi
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new BasicFrontControllerMySQLi();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers BasicFrontControllerMySQLi::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testFactory
     *
     * @covers BasicFrontControllerMySQLi::factory
     *
     * @todo   Implement testFactory().
     *
     * @return void
     */
    public function testFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testCascadeView
     *
     * @covers BasicFrontControllerMySQLi::cascadeView
     *
     * @todo   Implement testCascadeView().
     *
     * @return void
     */
    public function testCascadeView()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
