<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE."DataListMySQLi.php";
/**
 * Class DataListMySQLiTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/DataListMySQLiTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 22:59:53.
 *
 */
class DataListMySQLiTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object DataListMySQLi an instance of DataListMySQLi
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new DataListMySQLi();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers DataListMySQLi::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testFactory
     *
     * @covers DataListMySQLi::factory
     *
     * @todo   Implement testFactory().
     *
     * @return void
     */
    public function testFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetQuery
     *
     * @covers DataListMySQLi::setQuery
     *
     * @todo   Implement testSetQuery().
     *
     * @return void
     */
    public function testSetQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
