<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE."DropDownMySQLi.php";
/**
 * Class DropDownMySQLiTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/DropDownMySQLiTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 23:00:21.
 *
 */
class DropDownMySQLiTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object DropDownMySQLi an instance of DropDownMySQLi
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new DropDownMySQLi();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testInstance
     *
     * @covers DropDownMySQLi::instance
     *
     * @todo   Implement testInstance().
     *
     * @return void
     */
    public function testInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testFactory
     *
     * @covers DropDownMySQLi::factory
     *
     * @todo   Implement testFactory().
     *
     * @return void
     */
    public function testFactory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetQuery
     *
     * @covers DropDownMySQLi::setQuery
     *
     * @todo   Implement testSetQuery().
     *
     * @return void
     */
    public function testSetQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
