<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_CORE."MySQLLoader.php";
/**
 * Class MySQLLoaderTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/MySQLLoaderTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 23:01:18.
 *
 */
class MySQLLoaderTest 
    extends PHPUnit_Framework_TestCase
{
    /**
     * @var object MySQLLoader an instance of MySQLLoader
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new MySQLLoader();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSetFileName
     *
     * @covers MySQLLoader::setFileName
     *
     * @todo   Implement testSetFileName().
     *
     * @return void
     */
    public function testSetFileName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetDirectory
     *
     * @covers MySQLLoader::setDirectory
     *
     * @todo   Implement testSetDirectory().
     *
     * @return void
     */
    public function testSetDirectory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers MySQLLoader::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
