<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE."BasicGenerator.php";
/**
 * Class BasicGeneratorTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/BasicGeneratorTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:02:44.
 *
 */
class BasicGeneratorTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object BasicGenerator an instance of BasicGenerator
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new BasicGenerator();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSetTableName
     *
     * @covers BasicGenerator::setTableName
     *
     * @todo   Implement testSetTableName().
     *
     * @return void
     */
    public function testSetTableName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetFileDestination
     *
     * @covers BasicGenerator::setFileDestination
     *
     * @todo   Implement testSetFileDestination().
     *
     * @return void
     */
    public function testSetFileDestination()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetFileExtension
     *
     * @covers BasicGenerator::setFileExtension
     *
     * @todo   Implement testSetFileExtension().
     *
     * @return void
     */
    public function testSetFileExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetFileExtension
     *
     * @covers BasicGenerator::getFileExtension
     *
     * @todo   Implement testGetFileExtension().
     *
     * @return void
     */
    public function testGetFileExtension()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers BasicGenerator::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
