<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_GENERATORS_ABSTRACT . "BrowseGenerator.php";

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-12 at 13:40:39.
 */
class BrowseGeneratorTest
    extends BaseTest
{
    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $databaseConnection = databaseConnectionMySQLi::instance();
        $this->object = $this->getMockForAbstractClass('BrowseGenerator', array($databaseConnection));
    }
}
