<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE."DatabaseBackup.php";
/**
 * Class DatabaseBackupTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/DatabaseBackupTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:05:55.
 *
 */
class DatabaseBackupTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object DatabaseBackup an instance of DatabaseBackup
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new DatabaseBackup();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSetCommand
     *
     * @covers DatabaseBackup::setCommand
     *
     * @todo   Implement testSetCommand().
     *
     * @return void
     */
    public function testSetCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetCommand
     *
     * @covers DatabaseBackup::getCommand
     *
     * @todo   Implement testGetCommand().
     *
     * @return void
     */
    public function testGetCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testAppendCommand
     *
     * @covers DatabaseBackup::appendCommand
     *
     * @todo   Implement testAppendCommand().
     *
     * @return void
     */
    public function testAppendCommand()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetDatabase
     *
     * @covers DatabaseBackup::setDatabase
     *
     * @todo   Implement testSetDatabase().
     *
     * @return void
     */
    public function testSetDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetDatabase
     *
     * @covers DatabaseBackup::getDatabase
     *
     * @todo   Implement testGetDatabase().
     *
     * @return void
     */
    public function testGetDatabase()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetDestination
     *
     * @covers DatabaseBackup::setDestination
     *
     * @todo   Implement testSetDestination().
     *
     * @return void
     */
    public function testSetDestination()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetDestination
     *
     * @covers DatabaseBackup::getDestination
     *
     * @todo   Implement testGetDestination().
     *
     * @return void
     */
    public function testGetDestination()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetHost
     *
     * @covers DatabaseBackup::setHost
     *
     * @todo   Implement testSetHost().
     *
     * @return void
     */
    public function testSetHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetHost
     *
     * @covers DatabaseBackup::getHost
     *
     * @todo   Implement testGetHost().
     *
     * @return void
     */
    public function testGetHost()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetOptions
     *
     * @covers DatabaseBackup::setOptions
     *
     * @todo   Implement testSetOptions().
     *
     * @return void
     */
    public function testSetOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetOptions
     *
     * @covers DatabaseBackup::getOptions
     *
     * @todo   Implement testGetOptions().
     *
     * @return void
     */
    public function testGetOptions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetPassword
     *
     * @covers DatabaseBackup::setPassword
     *
     * @todo   Implement testSetPassword().
     *
     * @return void
     */
    public function testSetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetPassword
     *
     * @covers DatabaseBackup::getPassword
     *
     * @todo   Implement testGetPassword().
     *
     * @return void
     */
    public function testGetPassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetPort
     *
     * @covers DatabaseBackup::setPort
     *
     * @todo   Implement testSetPort().
     *
     * @return void
     */
    public function testSetPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetPort
     *
     * @covers DatabaseBackup::getPort
     *
     * @todo   Implement testGetPort().
     *
     * @return void
     */
    public function testGetPort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetProtocol
     *
     * @covers DatabaseBackup::setProtocol
     *
     * @todo   Implement testSetProtocol().
     *
     * @return void
     */
    public function testSetProtocol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetProtocol
     *
     * @covers DatabaseBackup::getProtocol
     *
     * @todo   Implement testGetProtocol().
     *
     * @return void
     */
    public function testGetProtocol()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetSocket
     *
     * @covers DatabaseBackup::setSocket
     *
     * @todo   Implement testSetSocket().
     *
     * @return void
     */
    public function testSetSocket()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetSocket
     *
     * @covers DatabaseBackup::getSocket
     *
     * @todo   Implement testGetSocket().
     *
     * @return void
     */
    public function testGetSocket()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetTables
     *
     * @covers DatabaseBackup::setTables
     *
     * @todo   Implement testSetTables().
     *
     * @return void
     */
    public function testSetTables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetTables
     *
     * @covers DatabaseBackup::getTables
     *
     * @todo   Implement testGetTables().
     *
     * @return void
     */
    public function testGetTables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetUser
     *
     * @covers DatabaseBackup::setUser
     *
     * @todo   Implement testSetUser().
     *
     * @return void
     */
    public function testSetUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetUser
     *
     * @covers DatabaseBackup::getUser
     *
     * @todo   Implement testGetUser().
     *
     * @return void
     */
    public function testGetUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testExecute
     *
     * @covers DatabaseBackup::execute
     *
     * @todo   Implement testExecute().
     *
     * @return void
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
