<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_GENERATORS_ABSTRACT."FormGenerator.php";
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-07 at 17:49:29.
 */
class formGeneratorTest
    extends BaseTest
{
    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('FormGenerator');
    }

    /** testExecute
     *
     * @covers FormGenerator::execute
     *
     * @return void
     */
    public function testExecute()
    {
        $this->expected = true;
        $this->actual = $this->object->execute();
        $this->assertEquals($this->expected, $this->actual);
    }

    /** testSetFormType
     *
     * @param string $value          the form type to generate
     * @param bool   $expectedResult true = success, false = failure
     *
     * @covers FormGenerator::setFormType
     *
     * @return void
     */
    public function testSetFormType($value, $expectedResult)
    {
        $this->expected = $expectedResult;
        $this->actual = $this->object->setFormType($value);
        $this->assertEquals($this->expected, $this->actual);
    }
}
