<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_GENERATORS_ABSTRACT."JSONObjectGenerator.php";
/**
 * Class JSONObjectGeneratorTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/JSONObjectGeneratorTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:09:59.
 *
 */
class JSONObjectGeneratorTest 
    extends PHPUnit_Framework_TestCase
{
    /**
     * @var object JSONObjectGenerator an instance of JSONObjectGenerator
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new JSONObjectGenerator();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }

    /** testSetRequestOrResponse
     *
     * @covers JSONObjectGenerator::setRequestOrResponse
     *
     * @todo   Implement testSetRequestOrResponse().
     *
     * @return void
     */
    public function testSetRequestOrResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetRequestOrResponse
     *
     * @covers JSONObjectGenerator::getRequestOrResponse
     *
     * @todo   Implement testGetRequestOrResponse().
     *
     * @return void
     */
    public function testGetRequestOrResponse()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetAgencyOrModel
     *
     * @covers JSONObjectGenerator::setAgencyOrModel
     *
     * @todo   Implement testSetAgencyOrModel().
     *
     * @return void
     */
    public function testSetAgencyOrModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetAgencyOrModel
     *
     * @covers JSONObjectGenerator::getAgencyOrModel
     *
     * @todo   Implement testGetAgencyOrModel().
     *
     * @return void
     */
    public function testGetAgencyOrModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testSetTypes
     *
     * @covers JSONObjectGenerator::setTypes
     *
     * @todo   Implement testSetTypes().
     *
     * @return void
     */
    public function testSetTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /** testGetTypes
     *
     * @covers JSONObjectGenerator::getTypes
     *
     * @todo   Implement testGetTypes().
     *
     * @return void
     */
    public function testGetTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
