<?php
require_once __DIR__ . "/../../../config/config.inc.php";
require_once AMPHIBIAN_CORE."PreloaderGenerator.php";
/**
 * Class PreloaderGeneratorTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/PreloaderGeneratorTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:10:30.
 *
 */
class PreloaderGeneratorTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object PreloaderGenerator an instance of PreloaderGenerator
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new PreloaderGenerator();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }
}
