<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_GENERATORS_ABSTRACT."sprocGeneratorCustom.php";
/**
 * Class sprocGeneratorCustomTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/sprocGeneratorCustomTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:11:05.
 *
 */
class SprocGeneratorCustomTest
    extends BaseTest
{
    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = $this->getMockForAbstractClass('SprocGeneratorCustom');
    }
}
