<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . ".." . DIRECTORY_SEPARATOR . "baseTest.php";
require_once AMPHIBIAN_GENERATORS_ABSTRACT."standardViewBuilder.php";
/**
 * Class standardViewBuilderTest
 *
 * @category 
 * @package  
 * @author   
 * @license  
 * @link     documentation/standardViewBuilderTest
 *
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 21:11:17.
 *
 */
class standardViewBuilderTest 
	extends PHPUnit_Framework_TestCase
{
    /**
     * @var object standardViewBuilder an instance of standardViewBuilder
     */
    protected $object;

    /** setUp
     *
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @return void
     */
    protected function setUp()
    {
        $this->object = new standardViewBuilder();
    }

    /** tearDown
     *
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @return void
     */
    protected function tearDown()
    {
    }
}
